#======================================================================
# Project settings
#======================================================================
# Only build master.
branches:
  only:
      - master

language: fortran

#======================================================================
# Environment
#======================================================================

# Code is Fortran.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - gfortran-6
      - g++-6
      - lcov

#======================================================================
# Build Matrix
#======================================================================
matrix:
   include:
     - os: linux
       compiler: gcc
       sudo: false
       dist: trusty

#======================================================================
# Docker, does not work on Mac
#======================================================================
services:
  - docker

#======================================================================
# Building
#======================================================================
before_install:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
          pip install --user cpp-coveralls
      fi

script:
  - date
  - docker build -t wrf_regtest .
  - date
  - docker images -a
  - date
  - docker run -d -t --name test_001 wrf_regtest
  - date
  - docker ps -a
  - date
  - docker exec test_001 ./script.csh BUILD CLEAN 34 1 em_real -d
  - OK=$?
  - echo "Return code from docker is $OK"
  - date
  - docker stop test_001
  - date
  - docker rmi wrf_regtest
  - date

#======================================================================
# Notifications
#======================================================================
notifications:
  email:
    recipients: gill@ucar.edu
    on_success: always
    on_failure: always

